### ISSUE TITLE
[DOC] Retrabalhar a Avaliação hierárquica de tarefas.

### ISSUE THREAD

**Issue by Eric-chagas** [Interacao-Humano-Computador/2022.2-UnbIdiomas#20]
## Descrição

Retrabalhar a Avaliação hierárquica de tarefas.

## Tarefas

- [ ] Adicionar mais opções nos fluxos
- [ ] Definir melhor os passos
- [ ] Melhorar Diagramas
- [ ] Adicionar legenda dos diagramas

## Critérios de Aceitação

- [ ] Cada fluxo da avaliação possui passos e planos
- [ ] Cada fluxo possuí um diagrama com texto descritivo dos planos, passos e hierarquia (na própria imagem)
- [ ] Cada diagrama possui uma legenda com os passos e planos

## Definição de Feito 

- [ ] Legendas em todas as tabelas e imagens com chamada no texto
- [ ] Referências
- [ ] Histórico de versões

**Comment by hgaldino05** [comment]
revisar depois
